name: tpc
version: "2.1-alpha"
main: com.censera.tpc.TpcPlugin
api-version: "26.3"
author: Censera
description: Small teleportation utility for Paper

commands:
  tpc:
    description: Open the teleportation menu.
    usage: /tpc [ask|here|accept|decline|bed|home|spawn]
    permission: tpc.command

  tpr:
    description: Reload tpc configuration.
    usage: /tpr
    permission: tpc.reload

  tpa:
    description: Request to teleport to a player.
    usage: /tpa [player|cancel|page <number>]
    permission: tpc.request

  tph:
    description: Ask a player to teleport to you.
    usage: /tph [player|cancel|page <number>]
    permission: tpc.here

  accept:
    description: Accept a teleport request.
    usage: /accept
    permission: tpc.accept

  decline:
    description: Decline a teleport request.
    usage: /decline
    permission: tpc.decline

  back:
    description: Teleport back to the previous location.
    usage: /back
    permission: tpc.back

  bed:
    description: Teleport to your bed.
    usage: /bed
    permission: tpc.bed

  home:
    description: Manage and teleport to homes.
    usage: /home [name|list|set <name> [is-primary]|delete <name>|primary <name>]
    permission: tpc.home

  spawn:
    description: Teleport to server spawn.
    usage: /spawn
    permission: tpc.spawn

  tpaccept:
    description: Alias for /accept.
    usage: /tpaccept
    permission: tpc.alternative.tpaccept

  tpdecline:
    description: Alias for /decline.
    usage: /tpdecline
    permission: tpc.alternative.tpdecline

  tpback:
    description: Alias for /back.
    usage: /tpback
    permission: tpc.alternative.tpback

  tpbed:
    description: Alias for /bed.
    usage: /tpbed
    permission: tpc.alternative.tpbed

  tphome:
    description: Alias for /home.
    usage: /tphome
    permission: tpc.alternative.tphome

  tpspawn:
    description: Alias for /spawn.
    usage: /tpspawn
    permission: tpc.alternative.tpspawn

permissions:
  tpc.command:
    default: true
  tpc.reload:
    default: op
  tpc.request:
    default: true
  tpc.here:
    default: true
  tpc.accept:
    default: true
  tpc.decline:
    default: true
  tpc.back:
    default: true
  tpc.bed:
    default: true
  tpc.home:
    default: true
  tpc.spawn:
    default: true
  tpc.alternative.tpaccept:
    default: true
  tpc.alternative.tpdecline:
    default: true
  tpc.alternative.tpback:
    default: true
  tpc.alternative.tpbed:
    default: true
  tpc.alternative.tphome:
    default: true
  tpc.alternative.tpspawn:
    default: true
